# -*- coding: utf-8 -*-

"""
@author: lucas
@Function:
@file: test_baidu2.py
@time: 2021/9/13 11:13 上午
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from time import sleep
import unittest
from utils.config import Config, DATA_PATH, REPORT_PATH
from utils.log import logger
from utils.file_reader import ExcelReader
from utils.HTMLTestRunner import HTMLTestRunner
from utils.mail import Email
from test.page.baidu_result_page import BaiDuMainPage, BaiDuResultPage
from sys import path



class TestBaiDu(unittest.TestCase):
    URL = Config().get('URL')
    excel = DATA_PATH + '/baidu.xlsx'

    def __init__(self, methodName: str = ...):
        super().__init__(methodName)
        self.title = None

    def sub_setUp(self):
        # 初始页面是main page，传入浏览器类型打开浏览器
        self.page = BaiDuMainPage(browser_type='firefox').get(self.URL, maximize_window=False)

    def sub_tearDown(self):
        self.page.quit()

    def test_search(self):
        datas = ExcelReader(self.excel).data
        for d in datas:
            with self.subTest(data=d):
                self.sub_setUp()
                self.page.search(d['search'])
                sleep(2)

                self.page = BaiDuResultPage(self.page)  # 页面跳转到result page
                links = self.page.result_links
                for link in links:
                    logger.info(link.text)
                self.assertNotEqual("selenium", link.text)
                self.assertEqual("selenium", link.text[0])
                # self.assertIn("selenium", link.text)
                self.sub_tearDown()


if __name__ == '__main__':
    mail = Config().get('mail')
    report = REPORT_PATH + mail.get('path')
    with open(report, 'w') as f:
        runner = HTMLTestRunner(f, verbosity=2, title='baidu Test Report', description='generated by Lucas.')
        runner.run(TestBaiDu('test_search'))
    e = Email(title=mail.get('title'),
              message=mail.get('message'),
              receiver=mail.get('receiver'),
              server=mail.get('server'),
              sender=mail.get('sender'),
              password=mail.get('password'),
              path=report
              )
    e.send()
