# -*- coding: utf-8 -*-

"""
@author: lucas
@Function:
@file: test_suite.py
@time: 2021/9/6 2:32 下午
"""
import sys

import unittest
# print(sys.path)
# sys.path.append('..')

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
#path.append('/Users/leiyuxing/PycharmProjects/TestFramework')

from utils.HTMLTestRunner import HTMLTestRunner
from utils.TestMathFunc import TestMathFunc
from utils.config import REPORT_PATH, Config
from utils.log import logger
from utils.mail import Email

if __name__ == '__main__':
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))
    mail = Config().get('mail')
    report = REPORT_PATH + mail.get('path')
    with open(report, 'w') as f:
        runner = HTMLTestRunner(stream=f,
                                title='MathFunc Test Report',
                                description='generated by Lucas.',
                                verbosity=2
                                )
        runner.run(suite)
    # e = Email(title=mail.get('title'),
    #           message=mail.get('message'),
    #           receiver=mail.get('receiver'),
    #           server=mail.get('server'),
    #           sender=mail.get('sender'),
    #           password=mail.get('password'),
    #           path=report
    #           )
    # e.send()
