zentao_data:
   # 我上传的文件服务器地址，如果需要统一域名下的话，可以起个服务再输入需要访问机器的ipv4地址
  server: "http://127.0.0.1:63342/"
  #钉钉机器人的webhook
  url: "https://oapi.dingtalk.com/robot/send?access_token=896ee0632303cf4cd12cd43df7e356d022ad77d9d11b661e086349b20c8a6cf4"
  sign_mark: "本周"
  markdown:
    title: "测试bug统计"
  is_at_all: True # @全体成员（在此可设置@特定某人）

